{% set name = "textwrap3" %}
{% set version = "0.9.2" %}
{% set bundle = "zip" %}
{% set hash_type = "sha256" %}
{% set hash = "5008eeebdb236f6303dcd68f18b856d355f6197511d952ba74bc75e40e0c3414" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - textwrap3

about:
  home: https://github.com/jonathaneunice/textwrap3
  # license_file: No license provided or described - assuming PSF since a backport; see https://github.com/jonathaneunice/textwrap3/issues/1
  license: PSF 2.0
  license_family: PSF
  summary: 'textwrap3 is a compatibility back-port of Python 3.6’s textwrap module that supports Python 2.6 forward. This makes a few new APIs such as shorten and the max_lines parameter available in a compatible way to all Python versions typically in current use.'
  doc_url: https://docs.python.org/3.6/library/textwrap.html
  dev_url: https://github.com/jonathaneunice/textwrap3

extra:
  recipe-maintainers:
    - pmlandwehr
