{% set version = "1.2.0a2" %}

package:
    name: ophyd
    version: {{ version }}

source:
    url: https://github.com/NSLS-II/ophyd/archive/v{{ version }}.tar.gz
    fn: ophyd-v{{ version }}.tar.gz

build:
    number: 0
    skip: True  # [py2k]
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - networkx
        - numpy
        - pyepics
        - python

test:
    imports:
        - ophyd

about:
    home: https://github.com/NSLS-II/ophyd
    license: BSD 3-Clause
