package:
    name: hdf5-lz4
    version: 0.2

source:
    git_url: https://github.com/dectris/HDF5Plugin.git
    git_tag: 8b3306f34fb9d1b248ac13bbc935180528270e65  # no tags in repo

build:
    number: 5

requirements:
    build:
        - hdf5 1.10.2
    run:
        - hdf5 1.10.2

about:
    home: https://github.com/dectris/HDF5Plugin
    license: BSD-2
