{% set year = "2019" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - analysis >=2019C2.0
    - caproto >=0.3
    - nslsii >=0.0.9
    - pyepics >=3.3.0
    - pyolog >=4.4.0
    - pyserial
