{% set year = "2018" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 2

requirements:
  run:
    - analysis
    - ophyd
    - pyepics
    - pyolog
