{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - analysis >=2018C2.0
    - caproto >=0.1.0a1
    - ophyd >=1.2.0a2
    - pyepics >=3.3.0
    - pyolog >=4.4.0
    - nslsii >=0.0.2
    - pyserial
