{% set name = "xpdan" %}
{% set version = "0.7.0" %}
{% set sha256 = "c1a7cd5b429207e80214eaed2f01ca7057d477600a4da6e50aff168a054a3c16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - scipy
    - matplotlib
    - pyyaml
    - scikit-beam
    - pyfai
    - pyxdameraulevenshtein
    - xray-vision
    - databroker
    - bluesky
    - rapidz
    - xpdsim
    - shed
    - xpdview
    - ophyd
    - xpdconf
    - xpdtools
    - mayavi

test:
  imports:
    - xpdan
    - xpdan.pipelines

about:
  home: http://github.com/xpdAcq/xpdAn
  license: BSD-3-Clause 
  license_family: BSD
  license_file: LICENSE
  summary: 'Analysis Tools for XPD'
  doc_url: http://xpdacq.github.io/xpdAn/
  dev_url: http://github.com/xpdAcq/xpdAn

extra:
  recipe-maintainers:
    - CJ-Wright
