package:
  name: doct
  version: 1.0.1

source:
  git_url: http://github.com/NSLS-II/doct
  git_rev: v1.0.1

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - six

test:
  imports:
    # Import all the packages
    - doct

about:
  home: http://github.com/NSLS-II/document
  license: BSD
