package:
  name: lmfit-c
  version: "8.2.2.post27"

source:
  git_url: https://github.com/NSLS-II/lmfit
  git_rev: 5f540ec733489970d1a190e51be2ded9e413e61a

build:
  number: 10

requirements:
  build:
    - cmake
    - gcc_linux-64

about:
  home: https://github.com/NSLS-II/lmfit
  license: FreeBSD
    
extra:
  recipe-maintainers:
    - stuwilkins
