{% set name = "databroker-elasticsearch" %}
{% set setupdata = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ setupdata['version'] }}

source:
  git_url: https://github.com/NSLS-II/databroker-elasticsearch
  git_rev: master

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.5
    - bluesky
    - databroker
    - elasticsearch

test:
  requires:
    - pytest
  source_files:
    - src/tests/
  commands:
    - pytest -vv -rxs src/tests

about:
  home: https://github.com/NSLS-II/databroker-elasticsearch
  summary: Utility for exporting metadata from databroker to Elasticsearch.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pavoljuhas
