{% set version = "0.1.0a8" %}
{% set setup_py = load_setup_py_data() %}

package:
    name: 'intake-bluesky'
    version: {{ version }}

source:
    git_url: https://github.com/bluesky/intake-bluesky
    git_rev: v{{ version }}

build:
    number: 3
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    skip: True  # [py2k]

requirements:
    build:
        - python
        - pip

    run:
        - python
        - dask
        - event-model >=1.8.0
        - intake !=0.5.0
        - intake-xarray
        - mongoquery
        - msgpack-numpy
        - msgpack-numpy  # to be split into extras or a separate package
        - msgpack-python
        - numpy
        - pandas
        - pymongo  # to be split into extras or a separate package
        - pyyaml  # undeclared by intake v0.4.1
        - requests
        - xarray

about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE
    summary: {{ setup_py.get('description') }}
