{% set name = "xpdacq" %}
{% set version = "0.9.1" %}
{% set sha256 = "46aa4580df4e8dab5d0908a757a9a25fec06ebc50bec86d415e4fc5bff76702a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - pyyaml
    - pandas
    - xlrd
    - pyfai
    - ipython
    - bluesky
    - xpdan
    - xpdsim
    - databroker
    - ophyd
    - xpdconf
 

test:
  imports:
    - xpdacq
    - xpdacq.xpdacq
    - xpdacq.beamtime

about:
  home: https://github.com/xpdAcq/xpdAcq
  license: BSD-3-Clause
  license_family: BSD 
  license_file: LICENSE
  summary: 'Acquisition packages for XPD-28 beamline at BNL'

  doc_url: http://xpdacq.github.io/xpdAcq/
  dev_url: https://github.com/xpdAcq/xpdAcq

extra:
  recipe-maintainers:
    - CJ-Wright 
