#!/bin/bash

set -e
rm -rf /tmp/$LOGNAME
if [ "$RAMDISK_DIR" == "" ]; then
  RAMDISK_DIR="/tmp/$LOGNAME/ramdisk"
  mkdir -p $RAMDISK_DIR
  echo "RAMDISK_DIR set to $RAMDISK_DIR"
else
  echo "RAMDISK_DIR already exists at $RAMDISK_DIR"
fi

# if the ramdisk dir does not already exist, then create a ramdisk!
if [ ! -d "$RAMDISK_DIR" ]; then
  chmod 777 "$RAMDISK_DIR"
  sudo mount -t tmpfs -o size=10G tmpfs "$RAMDISK_DIR"
fi

if [ "$CONDA_DIR" == "" ]; then
  CONDA_DIR="$RAMDISK_DIR/mc"
fi
if [ ! -d "$CONDA_DIR" ]; then
  # check and if we have a miniconda bash script available and run it if we do
  find ~/Downloads -iname *miniconda* -print | head -n 1 | xargs -I {} bash {} -b -p $CONDA_DIR
  # if conda dir still doesn't exist, download and install
  if [ ! -d "$CONDA_DIR" ]; then
    MC_PATH=/tmp/$LOGNAME/miniconda.sh
    echo Dowloading miniconda to $MC_PATH
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $MC_PATH
    bash "$MC_PATH" -b -p "$CONDA_DIR"
  fi
fi
# add some setup/teardown scripts
mkdir -p $CONDA_DIR/etc/conda/activate.d
echo "source $RAMDISK_DIR/.condabuildrc
mkdir -p ~/.config/binstar
echo 'url: https://pergamon.cs.nsls2.local:8443/api' > ~/.config/binstar/config.yaml" > $CONDA_DIR/etc/conda/activate.d/setup.sh
mkdir -p $CONDA_DIR/etc/conda/deactivate.d
echo "
unset RAMDISK_DIR
unset CONDA_DIR
unset CONDARC
unset HTTPS_PROXY
unset HTTP_PROXY
unset REQUESTS_CA_BUNDLE
unset BINSTAR_TOKEN
source ~/.bashrc" > $CONDA_DIR/etc/conda/deactivate.d/teardown.sh
# set up a condabuildrc file
echo "
export RAMDISK_DIR=$RAMDISK_DIR
export CONDA_DIR=$CONDA_DIR
export CONDARC=$RAMDISK_DIR/.condarc
export REQUESTS_CA_BUNDLE=/etc/certificates/ca_cs_nsls2_local.crt
export no_proxy=cs.nsls2.local
export HTTP_PROXY=http://proxy:8888
export HTTPS_PROXY=http://proxy:8888
" > "$RAMDISK_DIR/.condabuildrc"
# set up a custom condarc for the ramdisk env
echo "
channels:
- https://pergamon.cs.nsls2.local:8443/conda/nsls2-tag
- https://pergamon.cs.nsls2.local:8443/conda/anaconda
always_yes: true
show_channel_urls: true" > "$RAMDISK_DIR/.condarc"

# Init the logs
LOG_DIR=/home/edill/auto-build-logs/`date +%Y`/`date +%m`/`date +%d`
DEV_DIR=$LOG_DIR/dev
TAG_DIR=$LOG_DIR/tag
mkdir -p $LOG_DIR
mkdir -p $DEV_DIR
mkdir -p $TAG_DIR

logname=`date +%H.%M`
DEV_LOG="$DEV_DIR/$logname"
TAG_LOG="$TAG_DIR/$logname"

# init the conda directory
echo "CONDA_DIR=$CONDA_DIR"
source $CONDA_DIR/bin/activate $CONDA_DIR
conda install anaconda-client patchelf conda-build
conda remove conda-build --force

install ()
{
    git clone https://github.com/$1 /tmp/$LOGNAME/$1
    pushd $1
    python setup.py develop
    popd
}

# clean up conda-build and conda-build utils
set +e
# Remove conda installs
# conda remove conda-build conda-build-all --yes

# Uninstall with pip a few times in case there are multiple versions
# pip uninstall conda-build conda-build-all --yes
# pip uninstall conda-build conda-build-all --yes
echo "Install a dev build of conda-build"
install conda/conda-buld
echo "Install dev build of conda-build-all"
install scitools/conda-build-all
echo "Install dev build of conda-build-utils"
install ericdill/conda-build-utils

echo "Install conda 4.0.4"
CONDA_DIR=/tmp/$LOGNAME/conda
rm -rf $CONDA_DIR
git clone https://github.com/conda/conda $CONDA_DIR
cd $CONDA_DIR
git checkout 4.0.4
pip uninstall conda --yes
CONDA_DEFAULT_ENV='' python setup.py install


run_dev_build () {
  # set up a custom condarc for the dev builds
  echo "
  channels:
  - https://pergamon.cs.nsls2.local:8443/conda/nsls2-dev
  - https://pergamon.cs.nsls2.local:8443/conda/nsls2-tag
  - https://pergamon.cs.nsls2.local:8443/conda/anaconda
  always_yes: true
  show_channel_urls: true" > "$RAMDISK_DIR/.condarc"
  # run the dev build
  USERNAME=nsls2-dev
  echo `date`
  rm -rf /tmp/$LOGNAME/staged-recipes-dev
  CLONE_DIR=/tmp/$LOGNAME/staged-recipes-dev
  rm -rf $CLONE_DIR

  git clone https://github.com/NSLS-II/staged-recipes-dev $CLONE_DIR
  # allow failures on the conda-build commands
  set +e
  echo "========== Running py2 builds ==========" | tee -a $DEV_LOG.summary
  version="2.7"
  devbuild $CLONE_DIR/py2 --username $USERNAME --pyver $version --log $DEV_LOG.summary
  echo "========== Running py3 builds ==========" | tee -a $DEV_LOG.summary
  version="3.4 3.5"
  devbuild $CLONE_DIR/py3 --username $USERNAME --pyver $version --log $DEV_LOG.summary
  echo "========== Running pyall builds ==========" | tee -a $DEV_LOG.summary
  version="2.7 3.4 3.5"
  devbuild $CLONE_DIR/pyall/ --username $USERNAME --pyver $version --log $DEV_LOG.summary
}


run_tag_build() {
  # set up a custom condarc for the dev builds
  echo "
  channels:
  - https://pergamon.cs.nsls2.local:8443/conda/nsls2-tag
  - https://pergamon.cs.nsls2.local:8443/conda/anaconda
  always_yes: true
  show_channel_urls: true" > "$RAMDISK_DIR/.condarc"
  # run the tagged builds
  echo `date`
  USERNAME=nsls2-tag
  CLONE_DIR=/tmp/$LOGNAME/tagged-recipes
  rm -rf $CLONE_DIR
  git clone https://github.com/NSLS-II/auto-build-tagged-recipes $CLONE_DIR
  #cd ../staged-recipes
  #conda-build-all /tmp/staged-recipes/recipes --upload-channels edill --matrix-conditions "python >=3.4" --inspect-channels nsls2
  # allow failures on the conda-build commands
  set +e
  echo "========== Running py2 builds ==========" | tee -a $TAG_LOG.summary
  version="2.7"
  devbuild $CLONE_DIR/py2 --username $USERNAME --pyver $version --log $DEV_LOG.summary
  echo "========== Running py3 builds ==========" | tee -a $TAG_LOG.summary
  version="3.4 3.5"
  devbuild $CLONE_DIR/py3 --username $USERNAME --pyver $version --log $DEV_LOG.summary
  echo "========== Running pyall builds ==========" | tee -a $TAG_LOG.summary
  version="2.7 3.4 3.5"
  devbuild $CLONE_DIR/pyall --username $USERNAME --pyver $version --log $DEV_LOG.summary
  echo "========== Running pyall builds ==========" | tee -a $TAG_LOG.summary
  version="2.7 3.4 3.5"
  devbuild $CLONE_DIR/pyall --username $USERNAME --pyver $version --log $TAG_LOG.summary
  echo "========== Running nonpy builds ==========" | tee -a $TAG_LOG.summary
  version="3.5"
  devbuild $CLONE_DIR/nonpy --username $USERNAME --pyver $version --log $TAG_LOG.summary
  echo "========== Running scikit-beam builds ==========" | tee -a $TAG_LOG.summary
  version="2.7 3.4 3.5"
  devbuild $CLONE_DIR/skbeam-recipes/ --username $USERNAME --pyver $version --log $TAG_LOG.summary
  echo "========== Running sort-of-dev-but-actually-tag builds ==========" | tee -a $TAG_LOG.summary
  version="3.4 3.5"
  devbuild $CLONE_DIR/sort-of-dev-but-actually-tag/py3 --username $USERNAME --pyver $version --log $TAG_LOG.summary

}
#LOG=/tmp/build.log
run_dev_build |& tee -a $DEV_LOG
run_tag_build |& tee -a $TAG_LOG

echo "Removing download trash from logs"
sed '/% |/d' $DEV_LOG > /tmp/$LOGNAME/devlog
sed '/% |/d' $TAG_LOG > /tmp/$LOGNAME/taglog

echo "Emailing logs"
echo "Build status for $DATE
=============================================
DEV LOG SUMMARY

`cat $DEV_LOG.summary`

=============================================
TAG LOG SUMMARY
`cat $TAG_LOG.summary`
" | mutt -s "log test" edill@bnl.gov -y -a /tmp/$LOGNAME/devlog /tmp/$LOGNAME/taglog --
