package:
  name: kiwisolver
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_TAG_PLACEHOLDER') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER') }}

source:
  git_rev: master
  git_url: https://github.com/nucleic/kiwi
  patches:
    - setup.py.patch

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/nucleic/kiwi
  license: Modified BSD
  summary: 'A fast implementation of the Cassowary constraint solver'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
