{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: 16-id-lix-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - fabio
    - py4xs
    - lmfit >=0.9.9
