{% set name = "bluesky-browser" %}
{% set version = "0.1.0a5" %}
{% set sha256 = "c9c703494c3f49d0edc146a03b4f9de1873e88808cdd2d8963ab5f4d47311414" %}
{% set setup_py = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]
  entry_points:
    - bluesky-browser-qt = bluesky_browser.frameworks.qt.main:main
    - bluesky-browser = bluesky_browser.frameworks.qt.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bluesky
    - databroker >=1.0.0a1
    - event-model >=1.11.1
    - intake
    - jsonschema
    - matplotlib
    - ophyd  # for demo's example data generator -- maybe should be optional?
    - pyqt >=5.8
    - pyzmq
    - qtpy
    - suitcase-jsonl
    - tornado
    - traitlets

test:
  imports:
    - bluesky_browser
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'bluesky-browser --help'  # [linux]
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'bluesky-browser-qt --help'  # [linux]
    - bluesky-browser --help  # [not linux]
    - bluesky-browser-qt --help  # [not linux]

about:
  license: {{ setup_py.get('license') }}
  license_file: LICENSE
  summary: {{ setup_py.get('description') }}
