#!/usr/bin/env bash

# NOTE: This script has been adapted from content generated by github.com/conda-forge/conda-smithy
# UPLOAD_CHANNEL=lightsource2-dev

REPO_ROOT=$(cd "$(dirname "$0")/.."; pwd;)
IMAGE_NAME="nsls2/debian-with-miniconda:latest"
ANACONDA_SERVER_URL=${ANACONDA_SERVER_URL:-"https://api.anaconda.org"}
if [ $ANACONDA_SERVER_URL == "https://api.anaconda.org" ]; then
  CONDA_FORGE="conda-forge"
fi;

LOGDIR=/home/$LOGNAME/build-logs/`date +%Y`/`date +%m`/`date +%d`
mkdir -p $LOGDIR

cat << EOF | docker run -i \
                        -v ${REPO_ROOT}:/repo \
                        -v ${LOGDIR}:/logs
                        -a stdin -a stdout -a stderr \
                        $IMAGE_NAME \
                        bash || exit $?

if [ "${BINSTAR_TOKEN}" ];then
    export BINSTAR_TOKEN=${BINSTAR_TOKEN}
fi

mkdir -p ~/.config/binstar
echo "Setting anaconda server url to $ANACONDA_SERVER_URL"
echo "url: $ANACONDA_SERVER_URL" > ~/.config/binstar/config.yaml


echo "binstar_upload: false
always_yes: true
show_channel_urls: true
channels:" > ~/.condarc

if [ $ANACONDA_SERVER_URL == "https://api.anaconda.org" ]; then
  echo "- $UPLOAD_CHANNEL
- conda-forge
- defaults" >> ~/.condarc
else
  echo "- $UPLOAD_CHANNEL
- defaults" >> ~/.condarc
fi;

echo "contents of ~/.condarc"
cat ~/.condarc

conda install conda-build anaconda-client

LOGFILE="tag-`date +%H.%M`"

echo UPLOAD_CHANNEL=$UPLOAD_CHANNEL

# Unused, but needed by conda-build currently... :(
export CONDA_NPY='110'

export PYTHONUNBUFFERED=1

# once conda-execute 0.6.0 is available
# conda install conda-execute
# wget https://raw.githubusercontent.com/NSLS-II/conda-build-utils/master/nsls2_build_tools/build.py ~/build.py
# COMMAND="conda-execute ~/build.py"
pip install https://github.com/nsls-ii/conda-build-utils/zipball/master#egg=conda_build_utils
COMMAND="devbuild"
devbuild /repo/config -u $UPLOAD_CHANNEL --python 2.7 3.4 3.5 --numpy 1.10 1.11 --log /logs/$LOGFILE
devbuild /repo/recipes -u $UPLOAD_CHANNEL --python 2.7 3.4 3.5 --numpy 1.10 1.11 --log /logs/$LOGFILE
EOF
