#!/usr/bin/env bash

# NOTE: This script has been adapted from content generated by github.com/conda-forge/conda-smithy
CLONE_DIR=/tmp/$LOGNAME/staged-recipes-dev
USERNAME=lightsource2-dev

REPO_ROOT=$(cd "$(dirname "$0")/.."; pwd;)
IMAGE_NAME="ericdill/debian-conda-builder:latest"

config=$(cat <<CONDARC

channels:
 - lightsource2-dev
 - lightsource2
 - conda-forge
 - defaults

always_yes: true
show_channel_urls: True
track_features:
- nomkl
CONDARC
)

cat << EOF | docker run -i \
                        -v ${REPO_ROOT}:/repo \
                        -a stdin -a stdout -a stderr \
                        $IMAGE_NAME \
                        bash || exit $?

if [ "${BINSTAR_TOKEN}" ];then
    export BINSTAR_TOKEN=${BINSTAR_TOKEN}
fi

echo USERNAME=$USERNAME
echo CLONE_DIR=$CLONE_DIR

# Unused, but needed by conda-build currently... :(
export CONDA_NPY='110'

export PYTHONUNBUFFERED=1
echo "$config" > ~/.condarc

# A lock sometimes occurs with incomplete builds. The lock file is stored in build_artefacts.
conda clean --lock

conda install conda-build
conda install mock --yes
pip install https://github.com/ericdill/conda-build-all/zipball/include-test-deps#egg=conda-build-all
pip install https://github.com/ericdill/conda-build-utils/zipball/master#egg=conda-build-utils
conda info

# dont allow failures on the conda-build commands
set -e
pushd /repo
build_from_yaml build-directive.yaml -u $USERNAME

EOF
