# courteousy of CJ-Wright
main_format=dict(
    build='[![Build Status](https://travis-ci.org/lightsource2-recipes/{name}/{name}.svg?branch=master)](https://travis-ci.org/lightsource2-recipes/{name})',
    coverage='[![codecov](https://codecov.io/gh/lightsource2-recipes/{name}/{name}/branch/master/graph/badge.svg)](https://codecov.io/gh/lightsource2-recipes/{name}/{name}) ',
    health='[![Code Health](https://landscape.io/github/lightsource2-recipes/{name}/master/landscape.svg?style=flat)](https://landscape.io/github/lightsource2-recipes/{name}/master)',
    cf_version='[![Anaconda-Server Badge](https://anaconda.org/conda-forge/{name}/badges/version.svg)](https://anaconda.org/conda-forge/{name})',
    nsls_version='[![Anaconda-Server Badge](https://anaconda.org/lightsource2-tag/{name}/badges/version.svg)](https://anaconda.org/lightsource2-tag/{name})',
    downloads='[![Anaconda-Server Badge](https://anaconda.org/conda-forge/{name}/badges/downloads.svg)](https://anaconda.org/conda-forge/{name})')

a = '''|{name}|{build}|{coverage}|{health}|{cf_version} <br/> {nsls_version}|{downloads}|\n'''
c = '''# mission-control
Releases, Installers, Specs, and more!

# Build status
| Repo | Build | Coverage | Health | CF Version <br/> NSLS Version | Downloads|
|:-------:|:-----:|:--------:|:------:|:------:|:------:|
'''

modules = [
"03-id-hxn-collection",
"04-id-isr-collection",
"05-id-srx-collection",
"08-id-iss-analysis",
"11-id-chx-analysis",
"11-id-chx-collection",
"16-id-lix-analysis",
"23-id-1-csx1-analysis",
"23-id-1-csx1-collection",
"23-id-2-csx2-analysis",
"23-id-2-csx2-collection",
"28-id-2-xpd-analysis",
"28-id-2-xpd-collection",
"amostra",
"analysis",
"atom",
"attrs",
"bluesky",
"boltons",
"cairo-gobject-1.12.18",
"chxtools",
"collection",
"controls-doctor",
"csxtools",
"databroker",
"databroker-browser",
"datamuxer",
"doct",
"eiger-io",
"enaml",
"epics-base",
"event-model",
"exceptional",
"fabio",
"feedstock",
"ffmpeg",
"filestore",
"gobject-introspection-1.47.1",
"h5py",
"h5py-2.6.0",
"hdf5",
"hdf5-1.10.0",
"hdf5-lz4",
"historydict",
"hkl",
"hklpy",
"hkl-v5.0.0.2080",
"humanize",
"hxntools",
"hypothesis",
"ipyvolume",
"isstools",
"ixstools",
"kiwisolver",
"lmfit-0.8.3",
"lz4-c",
"metadataclient",
"metadataservice",
"metadatastore",
"mongoquery",
"nslsii",
"ophyd",
"oscars",
"perl",
"pims",
"portable-fs",
"portable-mds",
"ppmac",
"prettytable",
"py3cairo-1.10.0",
"pychx",
"pyepics",
"pyfai",
"pygobject3-3.12.0",
"pymongo-3.2.2",
"pympler",
"pyolog",
"pysmbc",
"pyxdameraulevenshtein",
"pyxrf",
"scikit-beam",
"shed",
"slicerator",
"sphinx-bootstrap-theme-0.4.5",
"streamz",
"streamz_ext",
"subprocess32",
"suitcase",
"super_state_machine-1.0",
"tifffile",
"trackpy-0.3.0",
"traittypes",
"tzlocal-1.1.2",
"x264",
"xattr",
"xpdacq",
"xpdan",
"xpdsim",
"xpdtools",
"xpdview",
"xraylib",
"xray-vision",
]

for b in modules:
    z = a.format(**main_format, name=b)
    c += z.format(name=b)
print(c)
with open('../README.md', 'w') as f:
    f.write(c)
