{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: 11-id-chx-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - boto3
    - chxtools
    - graphviz
    - line_profiler
    - memory_profiler
    - modestimage
    - papermill
