#!/bin/bash

# nsls2builder's token for anaconda.org. This has admin access to anaconda.org/lightsource2-dev
# and anaconda.org/lightsource2-tag
export SLACK_TOKEN="your token goes here"
export BINSTAR_TOKEN="your token goes here"
export SLACK_CHANNEL="bob-the-builder"
export UPLOAD_CHANNEL="lightsource2-dev"

$LOCKFILE="/tmp/$LOGNAME/devbuild.lock"
mkdir -p "/tmp/$LOGNAME"
if [ -e $LOCKFILE ]; then
  python -c "import slacker; slacker.Slacker($SLACK_TOKEN).chat.post_message('lock file exists at $LOCKFILE. Dev build aborting')"
else
  touch $LOCKFILE
fi;
LOGDIR="~/builds/`date +%Y`/`date +%m`/`date +%d`"
mkdir $LOGDIR -p
LOGFILE="$LOGDIR/`date +%H.%M`-dev"
CLONE_DIR="/tmp/$LOGNAME/dev/recipes"
rm -rf $CLONE_DIR
git clone https://github.com/nsls-ii/lightsource2-recipes $CLONE_DIR
pushd $CLONE_DIR/scripts

echo logging to $LOGFILE

./nsls2-dev-build.sh > $LOGFILE 2>&1

rm $LOCKFILE
