package:
  name: album
  version: 0.0.2

source:
  git_url: http://github.com/NSLS-II/album
  git_rev: v0.0.2

build:
  number: 0
  entry_points:
    - album = album.server:run

requirements:
  build:
    - python

  run:
    - python
    - bokeh
    - flask
    - databroker >=0.3.0
    - numpy

test:
  imports:
    - album
