{% set year = "2018" %}
{% set cycle = "3" %}
{% set version ="1" %}

package:
  name: analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - amostra  # [py3k]
    - bluesky >=1.4.0  # [py3k]
    - bluesky-kafka  # [py3k]
    - controls-doctor
    - dask
    - databroker >=0.11.3
    - databroker-browser
    - datamuxer
    - distributed
    - event-model >=1.6.0
    - fabio
    - ffmpeg
    - graphviz
    - h5py >=2.8.0
    - ipympl
    - ipython
    - ipywidgets
    - jupyter
    - numpy >=1.14.0
    - openpyxl
    - ophyd >=1.3.0
    - oscars
    - pyqt >=5.6.0
    - python >=3.6.0
    - python-graphviz
    - qt >=5.6.0
    - scikit-beam
    - suitcase
    - sympy
    - tornado <5.0.0
    - xlrd
    - xlwt
    - xray-vision
