package:
  name: channelarchiver
  version: 0.0.5

source:
  git_url: https://github.com/NSLS-II/channelarchiver.git
  git_rev: v0.0.5

build:
  number: 0

requirements:
  build:
    - setuptools
    - python
    - numpy
    - matplotlib
    - tzlocal

  run:
    - python
    - numpy
    - matplotlib
    - tzlocal

test:
  imports:
    - channelarchiver

about:
  home: http://github.com/NSLS-II/channelarchiver
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
