package:
  name: filestore
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GGIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/NSLS-II/filestore
  git_rev: master
  patches:
    - config.patch

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_py{{ py }}


requirements:
  build:
    - python
    - six

  run:
    - python
    - h5py
    - six
    - pyyaml
    - jsonschema
    - pims
    - tifffile
    - boltons
    - pymongo
    - doct

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - filestore
    - filestore.api
    - filestore.conf
    - filestore.file_writers
    - filestore.handlers

about:
  home: https://github.com/NSLS-II/filestore
  license: BSD
