{% set version = "1.4.1" %}

package:
    name: bluesky
    version: {{ version }}

source:
    git_url: https://github.com/nsls-ii/bluesky
    git_rev: v{{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python

    run:
        - cycler
        - databroker
        - event-model
        - historydict
        - ipython
        - jsonschema
        - lmfit
        - matplotlib
        - numpy
        - ophyd
        - python
        - pyzmq
        - super_state_machine
        - toolz
        - tqdm

test:
    imports:
        - bluesky

about:
    home: https://github.com/NSLS-II/bluesky
    license: BSD
